### PR TITLE
Fix ESLint warnings

### PR DESCRIPTION
**Pull request by mgrabovsky**

### CODE REVIEW

**Comment by Andrei-Stepanov** [comment]
https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects

I am not sure that we need this.

This is case where `[]` should be empty. It has special logic.

There are google: `react useeffect empty eslint`

I previously checked, it was not valid warning.

**Comment by mgrabovsky** [comment]
@Andrei-Stepanov I'm aware of that, but I don't think adding the variables to the list would hurt anything. Do you propose using `eslint-disable-next-line react-hooks/exhaustive-deps` instead in these cases instead?

**Comment by mgrabovsky** [comment]
OK, I've updated the PR to disable the warning selectively.

**Comment by mgrabovsky** [comment]
I don't think it's a good idea to disable the rule globally. We always want to make sure that we didn't forget any relevant variables and we can always disable the rule locally in these special cases.

**Comment by Andrei-Stepanov** [comment]
> @Andrei-Stepanov What do you think? Is this OK to merge?

yes, please

**Pull request merged**
