### PR TITLE
Move detailed test results to the top

### PR DESCRIPTION
**Pull request by mgrabovsky**
Move the component for displaying detailed test results (a.k.a. xunit) to the top of the artifact result component.

### CODE REVIEW

**Review by Andrei-Stepanov — COMMENTED** [review]
@mgrabovsky please backup this change with user request, contacts, some discussion.

From me:

I expand ci-system (test) to get insight about its environmet for 99% of time:

time run
contacts
owners
location
logs
notes
umb-message info

Moreover, number of xunint tests can be huge, and this will just:

**- makes actual user hard to find real contact-points.**
- **it is not obvious** that there are details about test.
- load web UI -> makes browser heavy
- makes more distruction. While dashboard is already overloaded of information.

Informaion about test must be visible and intuite to find.

With this approach it is un-intuite that at bottom can be some ci-system details.

**Comment by jankaluza** [comment]
@Andrei-Stepanov , In the old Dashboard, the test results were visible as more or less first thing when you expanded the test (there was just 40px high contact information in the old Dashboard vs. 400px high information in the new Dashboard) and I believe the users are used to this behavior. Why did it change in the new Dashboard - was there any user request or discussion about this change?

I personally *think* the users want to see the test results as a first thing so they can see what was wrong with their build. The main goal of package maintainer is to get the build through the gating and the only thing blocking this is a failed test, so I think it is the main thing package maintainer wants to see there. We can ask package maintainers, but until we do so, I would just show it similarly as in the old Dashboard, because people are used to see the test results as more or less first thing when expanding the test case.

**Comment by Andrei-Stepanov** [comment]
@jankaluza then issue is in representaion of contact information. It must stay at the top, otherwise users will go directly to OSCI each time, ignoring some inforamtion at the bottom.

Issue is in representation of contacts at top: I agree. Why I changed it? Because I was playing with it. Because it was work of consolidation of entries with Greenwave. Before each label was individually defined. Right now: they are dynamically created. 
I very support idea changing representation of contacts / links / buttons / logs / irc / .... all. But that must stay at top.

**Comment by mgrabovsky** [comment]
Abandoning this in favour of a future redesign.

**Pull request closed without merging**
